# These are supported funding model platforms

ko_fi: v1rtl
liberapay: v1rtl
custom:
  [
    "https://stakes.social/0xcEAddcD2D86A348163EB2385e8fA76776d0DBf6e",
    "https://v1rtl.site/support",
    "https://paypal.me/v1rtl",
    "https://qiwi.com/n/V1RTL",
    "https://yoomoney.ru/to/410014774355272",
  ]
issuehunt: talentlessguy
